adapter_name_or_path: /output/train_llama_sft_2k_3b/checkpoint-100
export_dir: /model/train_llama_sft_2k_3b
framework: vllm
generation_params:
  do_sample: false
  max_tokens: 32
generator_batch_size: 4
generator_max_input_len: 6144
generator_model: train_llama_mix800k_ckpt3000_3b
gpu_memory_utilization: 0.65
metric_setting:
  retrieval_recall_topk: 5
metrics:
- em
- f1
- acc
- precision
- recall
model2path:
  llama_3b: meta-llama--Llama-3.2-3B-Instruct/snapshots/0cb88a4f764b7a12671c53f0838cd831a0843b95

model_name_or_path: meta-llama--Llama-3.2-3B-Instruct/snapshots/0cb88a4f764b7a12671c53f0838cd831a0843b95
save_dir: log/
use_fid: false
