### model
model_name_or_path: model/train_llama_rationale_2k_8b_nolabel/checkpoint-300

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 64
deepspeed: ds_z2_offload_config.json

### dataset
dataset: critic_rationale_dpo_2k_8b_distill72b_nolabel_gold
max_samples: 800000
template: llama3

cutoff_len: 20480 # 8192 + 1024 * 2
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/train_llama_critic_rationale_dpo_2k_8b_distill72b_nolabel_dpo_gold
logging_steps: 50
save_steps: 300
plot_loss: true
overwrite_output_dir: true
report_to: wandb
run_name: train_llama_critic_rationale_dpo_2k_8b_distill72b_nolabel_dpo_gold

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5 # 5.0e-6 # 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 300